'use client'; 

// import type { Metadata } from "next";
import "./globals.css";

import { ThemeProvider, createTheme } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { AppBar, Button, Container, Toolbar } from "@mui/material";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

const theme = createTheme({
  palette: {
    primary: { main: '#1976d2' },
    secondary: { main: '#dc004e' },
  },
  typography : {
      
  }
});

const handleLogout = () => {
  localStorage.removeItem('token'); // Clear token on logout
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <body>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <AppBar position="static">
          <Toolbar>
            <Button href="/auth/sign-in" color="inherit">Login</Button>
            <Button href="/auth/sign-up" color="inherit">Register</Button>
            <Button href="/protected" color="inherit" onClick={handleLogout}>Logout</Button>
          </Toolbar>
        </AppBar>
        <Container>{children}</Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
